export interface WinnerEntry {
	year: number;
	division: string;
	winner: string;
}

export interface WinnersCategory {
	ladies: WinnerEntry[];
	mixed: WinnerEntry[];
	mens: WinnerEntry[];
}

export const winnersData: WinnersCategory = {
	ladies: [
		// Division 1 - Chris Cable Trophy
		{ year: 1983, division: 'Division 1', winner: 'Hooton A' },
		{ year: 1984, division: 'Division 1', winner: 'Helsby' },
		{ year: 1985, division: 'Division 1', winner: 'Tattenhall' },
		{ year: 1986, division: 'Division 1', winner: 'Tattenhall' },
		{ year: 1987, division: 'Division 1', winner: 'Tattenhall A' },
		{ year: 1988, division: 'Division 1', winner: 'Hoole' },
		{ year: 1989, division: 'Division 1', winner: 'Hoole A' },
		{ year: 1990, division: 'Division 1', winner: 'Hoole' },
		{ year: 1991, division: 'Division 1', winner: 'Whitby' },
		{ year: 1992, division: 'Division 1', winner: 'Whitby' },
		{ year: 1993, division: 'Division 1', winner: 'Hoole' },
		{ year: 1994, division: 'Division 1', winner: 'Tarvin' },
		{ year: 1995, division: 'Division 1', winner: 'Tarvin A' },
		{ year: 1996, division: 'Division 1', winner: 'Tarvin A' },
		{ year: 1997, division: 'Division 1', winner: 'Tarvin A' },
		{ year: 1998, division: 'Division 1', winner: 'Tarvin A' },
		{ year: 1999, division: 'Division 1', winner: 'Port Sunlight' },
		{ year: 2000, division: 'Division 1', winner: 'Penyfford' },
		{ year: 2001, division: 'Division 1', winner: 'Penyfford' },
		{ year: 2002, division: 'Division 1', winner: 'Hoole A' },
		{ year: 2003, division: 'Division 1', winner: 'Wrexham' },
		{ year: 2004, division: 'Division 1', winner: 'Cheshire Oaks C' },
		{ year: 2005, division: 'Division 1', winner: 'Cheshire Oaks A' },
		{ year: 2006, division: 'Division 1', winner: 'Mold' },
		{ year: 2007, division: 'Division 1', winner: 'Mold' },
		{ year: 2008, division: 'Division 1', winner: 'Mold' },
		{ year: 2009, division: 'Division 1', winner: 'Mold' },
		{ year: 2010, division: 'Division 1', winner: 'Wrexham' },
		{ year: 2011, division: 'Division 1', winner: 'Mold' },
		{ year: 2012, division: 'Division 1', winner: 'Mold' },
		{ year: 2013, division: 'Division 1', winner: 'Wrexham' },
		{ year: 2014, division: 'Division 1', winner: 'Mold' },
		{ year: 2015, division: 'Division 1', winner: 'Brymbo A' },
		{ year: 2016, division: 'Division 1', winner: 'Mold' },
		{ year: 2017, division: 'Division 1', winner: 'Mold' },
		{ year: 2018, division: 'Division 1', winner: 'Mold' },
		{ year: 2019, division: 'Division 1', winner: 'Brymbo' },
		{ year: 2021, division: 'Division 1', winner: 'Mold' },
		{ year: 2022, division: 'Division 1', winner: 'Mold' },
		{ year: 2023, division: 'Division 1', winner: 'Wrexham' },
		{ year: 2024, division: 'Division 1', winner: 'Wrexham' },
		{ year: 2025, division: 'Division 1', winner: 'Wrexham' },
		// Division 2
		{ year: 1986, division: 'Division 2', winner: 'Helsby' },
		{ year: 1987, division: 'Division 2', winner: 'Frodsham' },
		{ year: 1988, division: 'Division 2', winner: 'Tarvin' },
		{ year: 1989, division: 'Division 2', winner: 'Glan Aber' },
		{ year: 1990, division: 'Division 2', winner: 'Glan Aber' },
		{ year: 1991, division: 'Division 2', winner: 'Frodsham' },
		{ year: 1992, division: 'Division 2', winner: 'Chester B' },
		{ year: 1993, division: 'Division 2', winner: 'Frodsham' },
		{ year: 1994, division: 'Division 2', winner: 'Port Sunlight' },
		{ year: 1995, division: 'Division 2', winner: 'Helsby' },
		{ year: 1996, division: 'Division 2', winner: 'Penyfford' },
		{ year: 1997, division: 'Division 2', winner: 'Tattenhall' },
		{ year: 1998, division: 'Division 2', winner: 'Cheshire Oaks' },
		{ year: 1999, division: 'Division 2', winner: 'Hoole B' },
		{ year: 2000, division: 'Division 2', winner: 'Frodsham' },
		{ year: 2001, division: 'Division 2', winner: 'Chester' },
		{ year: 2002, division: 'Division 2', winner: 'Wrexham' },
		{ year: 2003, division: 'Division 2', winner: 'Cheshire Oaks C' },
		{ year: 2004, division: 'Division 2', winner: 'Cheshire Oaks B' },
		{ year: 2005, division: 'Division 2', winner: 'Mold' },
		{ year: 2006, division: 'Division 2', winner: 'Brymbo A' },
		{ year: 2007, division: 'Division 2', winner: 'Chester A' },
		{ year: 2008, division: 'Division 2', winner: 'Port Sunlight' },
		{ year: 2009, division: 'Division 2', winner: 'Wrexham' },
		{ year: 2010, division: 'Division 2', winner: 'Cheshire Oaks A' },
		{ year: 2011, division: 'Division 2', winner: 'Kelsall A' },
		{ year: 2012, division: 'Division 2', winner: 'Cheshire Oaks B' },
		{ year: 2013, division: 'Division 2', winner: 'Hoole' },
		{ year: 2014, division: 'Division 2', winner: 'Kelsall' },
		{ year: 2015, division: 'Division 2', winner: 'Glan Aber A' },
		{ year: 2016, division: 'Division 2', winner: 'Cheshire Oaks B' },
		{ year: 2017, division: 'Division 2', winner: 'Hoole' },
		{ year: 2018, division: 'Division 2', winner: 'Cheshire Oaks B' },
		{ year: 2019, division: 'Division 2', winner: 'Chester B' },
		{ year: 2021, division: 'Division 2', winner: 'Kelsall' },
		{ year: 2022, division: 'Division 2', winner: 'Wrexham' },
		{ year: 2023, division: 'Division 2', winner: 'Hollies A' },
		{ year: 2024, division: 'Division 2', winner: 'Chester A' },
		{ year: 2025, division: 'Division 2', winner: 'Helsby A' },
		// Division 3
		{ year: 2000, division: 'Division 3', winner: 'Cheshire Oaks B' },
		{ year: 2001, division: 'Division 3', winner: 'Wrexham' },
		{ year: 2002, division: 'Division 3', winner: 'Cheshire Oaks C' },
		{ year: 2003, division: 'Division 3', winner: 'Chester B' },
		{ year: 2004, division: 'Division 3', winner: 'Mold' },
		{ year: 2005, division: 'Division 3', winner: 'Hoylake' },
		{ year: 2006, division: 'Division 3', winner: 'Glan Aber B' },
		{ year: 2007, division: 'Division 3', winner: 'Port Sunlight' },
		{ year: 2008, division: 'Division 3', winner: 'Wrexham' },
		{ year: 2009, division: 'Division 3', winner: 'Chester B' },
		{ year: 2010, division: 'Division 3', winner: 'Frodsham A' },
		{ year: 2011, division: 'Division 3', winner: 'Glan Aber B' },
		{ year: 2012, division: 'Division 3', winner: 'Thornton Hough' },
		{ year: 2013, division: 'Division 3', winner: 'Glan Aber B' },
		{ year: 2014, division: 'Division 3', winner: 'Chester C' },
		{ year: 2015, division: 'Division 3', winner: 'Cheshire Oaks C' },
		{ year: 2016, division: 'Division 3', winner: 'Hoylake' },
		{ year: 2017, division: 'Division 3', winner: 'Hollies' },
		{ year: 2018, division: 'Division 3', winner: 'Glan Aber B' },
		{ year: 2019, division: 'Division 3', winner: 'Cheshire Oaks C' },
		{ year: 2021, division: 'Division 3', winner: 'Wrexham' },
		{ year: 2022, division: 'Division 3', winner: 'Thornton Hough' },
		{ year: 2023, division: 'Division 3', winner: 'Overton' },
		{ year: 2024, division: 'Division 3', winner: 'Malpas' },
		{ year: 2025, division: 'Division 3', winner: 'Tarvin' }
	],
	mixed: [
		// Division 1
		{ year: 1980, division: 'Division 1', winner: 'Glan Aber B' },
		{ year: 1981, division: 'Division 1', winner: 'Malpas A' },
		{ year: 1982, division: 'Division 1', winner: 'Malpas A' },
		{ year: 1983, division: 'Division 1', winner: 'Helsby A' },
		{ year: 1984, division: 'Division 1', winner: 'Hooton A' },
		{ year: 1985, division: 'Division 1', winner: 'Hooton A' },
		{ year: 1986, division: 'Division 1', winner: 'Hooton A' },
		{ year: 1987, division: 'Division 1', winner: 'Hooton A' },
		{ year: 1988, division: 'Division 1', winner: 'Hooton A' },
		{ year: 1989, division: 'Division 1', winner: 'Chester A' },
		{ year: 1990, division: 'Division 1', winner: 'Hoole A' },
		{ year: 1991, division: 'Division 1', winner: 'Whitby' },
		{ year: 1992, division: 'Division 1', winner: 'Hoole A' },
		{ year: 1993, division: 'Division 1', winner: 'Whitby' },
		{ year: 1994, division: 'Division 1', winner: 'Hooton A' },
		{ year: 1995, division: 'Division 1', winner: 'Hooton A' },
		{ year: 1996, division: 'Division 1', winner: 'Hooton A' },
		{ year: 1997, division: 'Division 1', winner: 'Hooton A' },
		{ year: 1998, division: 'Division 1', winner: 'Hooton A' },
		{ year: 1999, division: 'Division 1', winner: 'Hoole A' },
		{ year: 2000, division: 'Division 1', winner: 'Hooton A' },
		{ year: 2001, division: 'Division 1', winner: 'Hooton A' },
		{ year: 2002, division: 'Division 1', winner: 'Hooton A' },
		{ year: 2003, division: 'Division 1', winner: 'Hooton A' },
		{ year: 2004, division: 'Division 1', winner: 'Hooton A' },
		{ year: 2005, division: 'Division 1', winner: 'Cheshire Oaks A' },
		{ year: 2006, division: 'Division 1', winner: 'Glan Aber' },
		{ year: 2007, division: 'Division 1', winner: 'Mold A' },
		{ year: 2008, division: 'Division 1', winner: 'Cheshire oaks A' },
		{ year: 2009, division: 'Division 1', winner: 'Mold A' },
		{ year: 2010, division: 'Division 1', winner: 'Mold A' },
		{ year: 2011, division: 'Division 1', winner: 'Chester A' },
		{ year: 2012, division: 'Division 1', winner: 'Mold A' },
		{ year: 2013, division: 'Division 1', winner: 'Heswall' },
		{ year: 2014, division: 'Division 1', winner: 'Mold A' },
		{ year: 2015, division: 'Division 1', winner: 'Mold A' },
		{ year: 2016, division: 'Division 1', winner: 'Mold A' },
		{ year: 2017, division: 'Division 1', winner: 'Mold A' },
		{ year: 2018, division: 'Division 1', winner: 'Chester A' },
		{ year: 2019, division: 'Division 1', winner: 'Brymbo A' },
		{ year: 2021, division: 'Division 1', winner: 'Glan Aber A' },
		{ year: 2022, division: 'Division 1', winner: 'Mold A' },
		{ year: 2023, division: 'Division 1', winner: 'Hoole A' },
		{ year: 2024, division: 'Division 1', winner: 'Hoole A' },
		{ year: 2025, division: 'Division 1', winner: 'Hoole A' },
		// Division 2
		{ year: 1981, division: 'Division 2', winner: 'Tarvin B Upton' },
		{ year: 1982, division: 'Division 2', winner: 'Hooton B' },
		{ year: 1983, division: 'Division 2', winner: 'Tarvin B' },
		{ year: 1984, division: 'Division 2', winner: 'Chester B' },
		{ year: 1985, division: 'Division 2', winner: 'Shell' },
		{ year: 1986, division: 'Division 2', winner: 'Chester B' },
		{ year: 1987, division: 'Division 2', winner: 'Glan Aber A' },
		{ year: 1988, division: 'Division 2', winner: 'Hoole' },
		{ year: 1989, division: 'Division 2', winner: 'Tarvin A' },
		{ year: 1990, division: 'Division 2', winner: 'Whitby' },
		{ year: 1991, division: 'Division 2', winner: 'Hoole B' },
		{ year: 1992, division: 'Division 2', winner: 'Chester B' },
		{ year: 1993, division: 'Division 2', winner: 'Helsby A' },
		{ year: 1994, division: 'Division 2', winner: 'Frodsham' },
		{ year: 1995, division: 'Division 2', winner: 'Helsby A' },
		{ year: 1996, division: 'Division 2', winner: 'Tarvin A' },
		{ year: 1997, division: 'Division 2', winner: 'Helsby A' },
		{ year: 1998, division: 'Division 2', winner: 'Tarvin A' },
		{ year: 1999, division: 'Division 2', winner: 'Frodsham A' },
		{ year: 2000, division: 'Division 2', winner: 'Overton A' },
		{ year: 2001, division: 'Division 2', winner: 'Mold' },
		{ year: 2002, division: 'Division 2', winner: 'Overton A' },
		{ year: 2003, division: 'Division 2', winner: 'Cheshire Oaks' },
		{ year: 2004, division: 'Division 2', winner: 'Glan Aber B' },
		{ year: 2005, division: 'Division 2', winner: 'Mold A' },
		{ year: 2006, division: 'Division 2', winner: 'Chester C' },
		{ year: 2007, division: 'Division 2', winner: 'Hoole A' },
		{ year: 2008, division: 'Division 2', winner: 'Port Sunlight' },
		{ year: 2009, division: 'Division 2', winner: 'Tarvin A' },
		{ year: 2010, division: 'Division 2', winner: 'Cheshire Oaks A' },
		{ year: 2011, division: 'Division 2', winner: 'Tarvin A' },
		{ year: 2012, division: 'Division 2', winner: 'Heswall' },
		{ year: 2013, division: 'Division 2', winner: 'Chester B' },
		{ year: 2014, division: 'Division 2', winner: 'Mold B' },
		{ year: 2015, division: 'Division 2', winner: 'Chester B' },
		{ year: 2016, division: 'Division 2', winner: 'Mold B' },
		{ year: 2017, division: 'Division 2', winner: 'Chester B' },
		{ year: 2018, division: 'Division 2', winner: 'Wrexham A' },
		{ year: 2019, division: 'Division 2', winner: 'Chester B' },
		{ year: 2021, division: 'Division 2', winner: 'Hoole B' },
		{ year: 2022, division: 'Division 2', winner: 'Chester B' },
		{ year: 2023, division: 'Division 2', winner: 'Hoole B' },
		{ year: 2024, division: 'Division 2', winner: 'Cheshire Oaks A' },
		{ year: 2025, division: 'Division 2', winner: 'Hoole B' },
		// Division 3
		{ year: 1986, division: 'Division 3', winner: 'Helsby B' },
		{ year: 1987, division: 'Division 3', winner: 'Hoole' },
		{ year: 1988, division: 'Division 3', winner: 'Whitby A' },
		{ year: 1989, division: 'Division 3', winner: 'Hoole B' },
		{ year: 1990, division: 'Division 3', winner: 'Mold' },
		{ year: 1991, division: 'Division 3', winner: 'Glan Aber' },
		{ year: 1992, division: 'Division 3', winner: 'Overton' },
		{ year: 1993, division: 'Division 3', winner: 'Brymbo' },
		{ year: 1994, division: 'Division 3', winner: 'Kelsall' },
		{ year: 1995, division: 'Division 3', winner: 'Overton B' },
		{ year: 1996, division: 'Division 3', winner: 'Helsby B' },
		{ year: 1997, division: 'Division 3', winner: 'Bickerton' },
		{ year: 1998, division: 'Division 3', winner: 'Glan Aber B' },
		{ year: 1999, division: 'Division 3', winner: 'Bickerton' },
		{ year: 2000, division: 'Division 3', winner: 'Hooton B' },
		{ year: 2001, division: 'Division 3', winner: 'Chester C' },
		{ year: 2002, division: 'Division 3', winner: 'Cheshire Oaks' },
		{ year: 2003, division: 'Division 3', winner: 'Brymbo A' },
		{ year: 2004, division: 'Division 3', winner: 'Hollies' },
		{ year: 2005, division: 'Division 3', winner: 'Cheshire oaks B' },
		{ year: 2006, division: 'Division 3', winner: 'Overton A' },
		{ year: 2007, division: 'Division 3', winner: 'Port Sunlight' },
		{ year: 2008, division: 'Division 3', winner: 'Upton A' },
		{ year: 2009, division: 'Division 3', winner: 'Wrexham A' },
		{ year: 2010, division: 'Division 3', winner: 'Wrexham B' },
		{ year: 2011, division: 'Division 3', winner: 'Heswall' },
		{ year: 2012, division: 'Division 3', winner: 'Mold B' },
		{ year: 2013, division: 'Division 3', winner: 'Chester C' },
		{ year: 2014, division: 'Division 3', winner: 'Glan Aber B' },
		{ year: 2015, division: 'Division 3', winner: 'Chester C' },
		{ year: 2016, division: 'Division 3', winner: 'Upton A' },
		{ year: 2017, division: 'Division 3', winner: 'Brymbo B' },
		{ year: 2018, division: 'Division 3', winner: 'Wrexham' },
		{ year: 2019, division: 'Division 3', winner: 'Hoole B' },
		{ year: 2021, division: 'Division 3', winner: 'Helsby' },
		{ year: 2022, division: 'Division 3', winner: 'Port Sunlight' },
		{ year: 2023, division: 'Division 3', winner: 'Wrexham C' },
		{ year: 2024, division: 'Division 3', winner: 'Hooton' },
		{ year: 2025, division: 'Division 3', winner: 'Heswall' },
		// Division 4
		{ year: 2003, division: 'Division 4', winner: 'Hollies' },
		{ year: 2004, division: 'Division 4', winner: 'Cheshire Oaks B' },
		{ year: 2005, division: 'Division 4', winner: 'Mold B' },
		{ year: 2006, division: 'Division 4', winner: 'Cheshire Oaks C' },
		{ year: 2007, division: 'Division 4', winner: 'Old Hall' },
		{ year: 2008, division: 'Division 4', winner: 'Wrexham' },
		{ year: 2009, division: 'Division 4', winner: 'Wrexham B' },
		{ year: 2010, division: 'Division 4', winner: 'Heswall' },
		{ year: 2011, division: 'Division 4', winner: 'Hooton B' },
		{ year: 2012, division: 'Division 4', winner: 'Hoylake' },
		{ year: 2013, division: 'Division 4', winner: 'Brymbo C' },
		{ year: 2014, division: 'Division 4', winner: 'Mold D' },
		{ year: 2015, division: 'Division 4', winner: 'Hoylake' }
	],
	mens: [
		// Division 1
		{ year: 1980, division: 'Division 1', winner: 'Hoole A' },
		{ year: 1981, division: 'Division 1', winner: 'Neston' },
		{ year: 1982, division: 'Division 1', winner: 'Heswall A' },
		{ year: 1983, division: 'Division 1', winner: 'Heswall A' },
		{ year: 1984, division: 'Division 1', winner: 'Malpas A' },
		{ year: 1985, division: 'Division 1', winner: 'Heswall A' },
		{ year: 1986, division: 'Division 1', winner: 'Heswall A' },
		{ year: 1987, division: 'Division 1', winner: 'Heswall A' },
		{ year: 1988, division: 'Division 1', winner: 'Hoole A' },
		{ year: 1989, division: 'Division 1', winner: 'Chester A' },
		{ year: 1990, division: 'Division 1', winner: 'Chester A' },
		{ year: 1991, division: 'Division 1', winner: 'Chester A' },
		{ year: 1992, division: 'Division 1', winner: 'Chester A' },
		{ year: 1993, division: 'Division 1', winner: 'Port Sunlight' },
		{ year: 1994, division: 'Division 1', winner: 'Heswall A' },
		{ year: 1995, division: 'Division 1', winner: 'Heswall A' },
		{ year: 1996, division: 'Division 1', winner: 'Heswall A' },
		{ year: 1997, division: 'Division 1', winner: 'Port Sunlight' },
		{ year: 1998, division: 'Division 1', winner: 'Heswall A' },
		{ year: 1999, division: 'Division 1', winner: 'Heswall A' },
		{ year: 2000, division: 'Division 1', winner: 'Port Sunlight A' },
		{ year: 2001, division: 'Division 1', winner: 'Port Sunlight A' },
		{ year: 2002, division: 'Division 1', winner: 'Cheshire Oaks A' },
		{ year: 2003, division: 'Division 1', winner: 'Wrexham A' },
		{ year: 2004, division: 'Division 1', winner: 'Heswall A' },
		{ year: 2005, division: 'Division 1', winner: 'Cheshire Oaks A' },
		{ year: 2006, division: 'Division 1', winner: 'Heswall A' },
		{ year: 2007, division: 'Division 1', winner: 'Cheshire Oaka A' },
		{ year: 2008, division: 'Division 1', winner: 'Heswall A' },
		{ year: 2009, division: 'Division 1', winner: 'Heswall B' },
		{ year: 2010, division: 'Division 1', winner: 'Heswall A' },
		{ year: 2011, division: 'Division 1', winner: 'Glan Aber A' },
		{ year: 2012, division: 'Division 1', winner: 'Wrexham A' },
		{ year: 2013, division: 'Division 1', winner: 'Wrexham A' },
		{ year: 2014, division: 'Division 1', winner: 'Glan Aber' },
		{ year: 2015, division: 'Division 1', winner: 'Glan Aber A' },
		{ year: 2016, division: 'Division 1', winner: 'Heswall A' },
		{ year: 2017, division: 'Division 1', winner: 'Heswall A' },
		{ year: 2018, division: 'Division 1', winner: 'Glan Aber A' },
		{ year: 2019, division: 'Division 1', winner: 'Glan Aber A' },
		{ year: 2021, division: 'Division 1', winner: 'Hoylake' },
		{ year: 2022, division: 'Division 1', winner: 'Hoole A' },
		{ year: 2023, division: 'Division 1', winner: 'Hoylake' },
		{ year: 2024, division: 'Division 1', winner: 'Hoole A' },
		{ year: 2025, division: 'Division 1', winner: 'Hoole A' },
		// Division 2
		{ year: 1981, division: 'Division 2', winner: 'Heswall B' },
		{ year: 1982, division: 'Division 2', winner: 'Hoole B' },
		{ year: 1983, division: 'Division 2', winner: 'Chester' },
		{ year: 1984, division: 'Division 2', winner: 'Hoole B' },
		{ year: 1985, division: 'Division 2', winner: 'Hooton' },
		{ year: 1986, division: 'Division 2', winner: 'Hoole B' },
		{ year: 1987, division: 'Division 2', winner: 'Tarvin' },
		{ year: 1988, division: 'Division 2', winner: 'Hoole B' },
		{ year: 1989, division: 'Division 2', winner: 'Thornton Hough A' },
		{ year: 1990, division: 'Division 2', winner: 'Frodsham' },
		{ year: 1991, division: 'Division 2', winner: 'Brymbo A' },
		{ year: 1992, division: 'Division 2', winner: 'Chester B' },
		{ year: 1993, division: 'Division 2', winner: 'Chester C' },
		{ year: 1994, division: 'Division 2', winner: 'Chester C' },
		{ year: 1995, division: 'Division 2', winner: 'Tarvin A' },
		{ year: 1996, division: 'Division 2', winner: 'Thorndale A' },
		{ year: 1997, division: 'Division 2', winner: 'Brymbo B' },
		{ year: 1998, division: 'Division 2', winner: 'Chester C' },
		{ year: 1999, division: 'Division 2', winner: 'Brymbo A' },
		{ year: 2000, division: 'Division 2', winner: 'Tattenhall' },
		{ year: 2001, division: 'Division 2', winner: 'Cheshire Oaks A' },
		{ year: 2002, division: 'Division 2', winner: 'Wrexham A' },
		{ year: 2003, division: 'Division 2', winner: 'Hoylake A' },
		{ year: 2004, division: 'Division 2', winner: 'Hoole A' },
		{ year: 2005, division: 'Division 2', winner: 'Cheshire Oaks B' },
		{ year: 2006, division: 'Division 2', winner: 'Hoole A' },
		{ year: 2007, division: 'Division 2', winner: 'Chester A' },
		{ year: 2008, division: 'Division 2', winner: 'Heswall C' },
		{ year: 2009, division: 'Division 2', winner: 'Upton A' },
		{ year: 2010, division: 'Division 2', winner: 'Chester A' },
		{ year: 2011, division: 'Division 2', winner: 'Wrexham B' },
		{ year: 2012, division: 'Division 2', winner: 'Brymbo A' },
		{ year: 2013, division: 'Division 2', winner: 'Hollies' },
		{ year: 2014, division: 'Division 2', winner: 'Heswall A' },
		{ year: 2015, division: 'Division 2', winner: 'Tarvin A' },
		{ year: 2016, division: 'Division 2', winner: 'Hollies A' },
		{ year: 2017, division: 'Division 2', winner: 'Wrexham A' },
		{ year: 2018, division: 'Division 2', winner: 'Hoylake' },
		{ year: 2019, division: 'Division 2', winner: 'Chester B' },
		{ year: 2021, division: 'Division 2', winner: 'Wrexham A' },
		{ year: 2022, division: 'Division 2', winner: 'Heswall' },
		{ year: 2023, division: 'Division 2', winner: 'Chester A' },
		{ year: 2024, division: 'Division 2', winner: 'Hoole B' },
		{ year: 2025, division: 'Division 2', winner: 'Hollies B' },
		// Division 3
		{ year: 1984, division: 'Division 3', winner: 'Hooton' },
		{ year: 1985, division: 'Division 3', winner: 'Tarvin' },
		{ year: 1986, division: 'Division 3', winner: 'Kelsall' },
		{ year: 1987, division: 'Division 3', winner: 'Malpas C' },
		{ year: 1988, division: 'Division 3', winner: 'Chester C' },
		{ year: 1989, division: 'Division 3', winner: 'Frodsham' },
		{ year: 1990, division: 'Division 3', winner: 'Heswall B' },
		{ year: 1991, division: 'Division 3', winner: 'County Officers' },
		{ year: 1992, division: 'Division 3', winner: 'Chester D' },
		{ year: 1993, division: 'Division 3', winner: 'Malpas B' },
		{ year: 1994, division: 'Division 3', winner: 'Helsby' },
		{ year: 1995, division: 'Division 3', winner: 'Thorndale' },
		{ year: 1996, division: 'Division 3', winner: 'Hoole C' },
		{ year: 1997, division: 'Division 3', winner: 'Tattenhall' },
		{ year: 1998, division: 'Division 3', winner: 'Glan Aber' },
		{ year: 1999, division: 'Division 3', winner: 'Hoylake B' },
		{ year: 2000, division: 'Division 3', winner: 'Hoole C' },
		{ year: 2001, division: 'Division 3', winner: 'Wrexham A' },
		{ year: 2002, division: 'Division 3', winner: 'Hoylake A' },
		{ year: 2003, division: 'Division 3', winner: 'Cheshire Oaks C' },
		{ year: 2004, division: 'Division 3', winner: 'Heswall B' },
		{ year: 2005, division: 'Division 3', winner: 'Glan Aber A' },
		{ year: 2006, division: 'Division 3', winner: 'Christleton' },
		{ year: 2007, division: 'Division 3', winner: 'Heswall C' },
		{ year: 2008, division: 'Division 3', winner: 'Upton' },
		{ year: 2009, division: 'Division 3', winner: 'Heswall C' },
		{ year: 2010, division: 'Division 3', winner: 'Port Sunlight A' },
		{ year: 2011, division: 'Division 3', winner: 'Brymbo A' },
		{ year: 2012, division: 'Division 3', winner: 'Tarvin B' },
		{ year: 2013, division: 'Division 3', winner: 'Wrexham C' },
		{ year: 2014, division: 'Division 3', winner: 'Glan Aber B' },
		{ year: 2015, division: 'Division 3', winner: 'Chester B' },
		{ year: 2016, division: 'Division 3', winner: 'Old Hall' },
		{ year: 2017, division: 'Division 3', winner: 'Malpas' },
		{ year: 2018, division: 'Division 3', winner: 'Mold' },
		{ year: 2019, division: 'Division 3', winner: 'Hoole C' },
		{ year: 2021, division: 'Division 3', winner: 'Hollies B' },
		{ year: 2022, division: 'Division 3', winner: 'Mold' },
		{ year: 2023, division: 'Division 3', winner: 'Wrexham C' },
		{ year: 2024, division: 'Division 3', winner: 'Cheshire Oaks' },
		{ year: 2025, division: 'Division 3', winner: 'Glan Aber B' },
		// Division 4 - Keith Wells Trophy
		{ year: 2001, division: 'Division 4 (Keith Wells Trophy)', winner: 'Cheshire Oaks B' },
		{ year: 2002, division: 'Division 4 (Keith Wells Trophy)', winner: 'Cheshire Oaks C' },
		{ year: 2003, division: 'Division 4 (Keith Wells Trophy)', winner: 'Wrexham B' },
		{ year: 2004, division: 'Division 4 (Keith Wells Trophy)', winner: 'Port Sunlight B' },
		{ year: 2005, division: 'Division 4 (Keith Wells Trophy)', winner: 'Christleton' },
		{ year: 2006, division: 'Division 4 (Keith Wells Trophy)', winner: 'Heswall C' },
		{ year: 2007, division: 'Division 4 (Keith Wells Trophy)', winner: 'Upton' },
		{ year: 2008, division: 'Division 4 (Keith Wells Trophy)', winner: 'Wrexham B' },
		{ year: 2009, division: 'Division 4 (Keith Wells Trophy)', winner: 'Upton B' },
		{ year: 2010, division: 'Division 4 (Keith Wells Trophy)', winner: 'Wrexham C' },
		{ year: 2011, division: 'Division 4 (Keith Wells Trophy)', winner: 'Mold' },
		{ year: 2012, division: 'Division 4 (Keith Wells Trophy)', winner: 'Chester C' },
		{ year: 2013, division: 'Division 4 (Keith Wells Trophy)', winner: 'Mold' },
		{ year: 2014, division: 'Division 4 (Keith Wells Trophy)', winner: 'Wrexham D' },
		{ year: 2015, division: 'Division 4 (Keith Wells Trophy)', winner: 'Old Hall' },
		{ year: 2016, division: 'Division 4 (Keith Wells Trophy)', winner: 'Tarvin B' }
	]
};
